server:
  port: 7001
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  freemarker:
    cache: false
    template-loader-path: classpath:template/freemarker
    prefer-file-system-access: false

  datasource:
    # 非hikari使用url配置
    url: jdbc:mariadb://172.10.11.34:3306/bvspcs
    username: root
    password: root
mybatis:
  dialect: org.apache.ibatis.dialect.MariadbDialect # org.apache.ibatis.dialect.OracleDialect
  base-package: com.kong.dao
  aliases-package: com.kong.data
  mapper-locations: classpath*:com/kong/mapping/*.xml
  underscore-to-camel-case: true